baseURL = "/"
languageCode = "en-us"
title = "Asad Advik"
theme = "asadadvik"
paginate = 4

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[permalinks]
  posts = "blog/:title"

